name: habitiq
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  
  # Core Streamlit Application Dependencies
  - streamlit>=1.28.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - plotly>=5.15.0
  - altair>=5.0.0
  - joblib>=1.3.0
    
  # Additional useful packages
  - pip
  
